weather:
  api:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spring:
  server:
    port: 8081
    servlet:
      context-path: /journal
  redis:
    host: redis.redns.redis-cloud.com
    port: 15641
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  data:
    mongodb:
      uri: mongodb+srv://xxxxxxxxxxxxx:xxxxxxxxxxx@cluster0.mongodb.net/?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxxxxx@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxx' password='xxxxxxxxxxxxxx';
      session:
        timeout:
          ms: 45000